# Generated by Django 4.1.5 on 2023-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=60)),
                ('phonenumber', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('phoneEmail', models.CharField(max_length=10)),
                ('freelance', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
    ]
