# Generated by Django 4.1.5 on 2023-05-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='freelance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='phoneEmail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='phonenumber',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='about',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
