# Generated by Django 3.2.17 on 2023-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='age',
        ),
        migrations.RemoveField(
            model_name='about',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='about',
            name='city',
        ),
        migrations.RemoveField(
            model_name='about',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='about',
            name='freelance',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phoneEmail',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='about',
            name='website',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
