# Generated by Django 3.2.17 on 2023-06-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20230611_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Task',
        ),
    ]
